apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-db-frontend
  labels:
    app: management-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-frontend
  template:
    metadata:
      labels:
        app: management-frontend
    spec:
      containers:
        - name: management
          image: group3_management:latest
          imagePullPolicy: Never
          env:
            - name: DB_HANDLER_URI
              value: http://dbhandler:9999/v1/
            - name: SERVER_URI
              value: http://localhost:8090/
          ports:
            - containerPort: 8090

