apiVersion: v1
kind: Service
metadata:
  name: managementservice
spec:
  selector:
    app: management-frontend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer
